apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: governance-policy-propagator-fm3n
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: governance-policy-propagator-fm3n
    app.kubernetes.io/part-of: governance-policy-propagator
  name: governance-policy-propagator-fm3n
  namespace: red-hat-acm-tenant
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: governance-policy-propagator-fm3n
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: governance-policy-propagator-fm3n
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:66db731bb49503d337c6f10f83ba0521209c196a7f38ea9620b5139fe305cb79
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
